### PR TITLE
Npm dependencies update

### PR DESCRIPTION
**Pull request by Pavel-Durov**
I've noticed the **DUMCONSTANTIN** tag with **out of date**. So I decided to open another PR.

Ran a few test locally, seems to be nonbreaking change.

This PR contains **acorn** and **ast-types** version updates.

### CODE REVIEW

**Comment by dumconstantin** [comment]
All green now! :+1:

**Comment by dumconstantin** [comment]
By the way, how are you using ` ramda-loader ` and how has it worked out for you so far?

**Comment by Pavel-Durov** [comment]
I was upgrading `webpack` version from 1 to 3 with my web team while integrating `ramda` library into our code base. I explored available plugins and found this one. Now, when it supports `webpack 3` I can check it fully in my project :)

**Comment by dumconstantin** [comment]
Great to hear it's working out for you and your team. Hope this plugin gives you an extra boost in productivity!

**Pull request merged**
